image = "nvcr.io/nvidia/pytorch:24.05-py3"

mounts = [
    "/capstor",
    "/iopsstor",
    "/users/${USER}/interleaving-audio-dataset",
    "/capstor/scratch/cscs/${USER}/thorsten-de", # Mount Data 
    "/users/${USER}/.edf",
    "/users/${USER}/.local/bin/uv",
    "/users/${USER}/.cache"
] 

workdir = "${HOME}/interleaving-audio-dataset"

[annotations]
com.hooks.aws_ofi_nccl.enabled = "true" 
com.hooks.aws_ofi_nccl.variant = "cuda12"

[env]
NCCL_DEBUG = "INFO" 
CUDA_CACHE_DISABLE = "1" 
TORCH_NCCL_ASYNC_ERROR_HANDLING = "1" 
MPICH_GPU_SUPPORT_ENABLED = "0"
HF_HOME = "/users/${USER}/.cache/huggingface"